# Generated by Django 2.1.15 on 2020-01-30 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='elient',
        ),
    ]
