# Generated by Django 2.1.15 on 2020-01-30 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200130_1748'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'default_permissions': {'view', 'add', 'change', 'delete'}},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'default_permissions': {'view', 'add', 'change', 'delete'}},
        ),
    ]
