# Generated by Django 2.1.15 on 2020-01-30 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200130_2124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'default_permissions': {'view'}},
        ),
    ]
